version: '3'
services:
  #mongodb://drinks:yINIitqSQ6WFRf2HIZZEnJXNDSY3cG0Fg04mFtGJAjpi9E1q9u@localhost:27017/AGxo1pcAlZvhzR0hRF26yd2i3
  mongo:
    container_name: drinks-mongo-db
    image: mongo:7.0-rc-jammy
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=yINIitqSQ6WFRf2HIZZEnJXNDSY3cG0Fg04mFtGJAjpi9E1q9u
      - MONGO_INITDB_DATABASE=AGxo1pcAlZvhzR0hRF26yd2i3
      - MONGO_INITDB_USER=drinks
      - MONGO_INITDB_PWD=yINIitqSQ6WFRf2HIZZEnJXNDSY3cG0Fg04mFtGJAjpi9E1q9u
    volumes:
      - "/mongo/drinks/data:/data/db"
      - "./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro"
    ports:
      - "27017:27017"
